// ============================================================================
// Pact Provider Test: Workflow
// Verifies that the Edge Functions meet the consumer's expectations
// ============================================================================

import { Verifier } from '@pact-foundation/pact';
import * as path from 'node:path';
import { providerConfig } from '../config';

describe('Workflow API Provider Verification', () => {
  it('validates the expectations of the web consumer', async () => {
    const opts = {
      provider: providerConfig.provider,
      
      // Provider base URL (Edge Functions endpoint)
      providerBaseUrl: providerConfig.providerBaseUrl,
      
      // Pact files to verify (generated by consumer tests)
      pactUrls: [
        path.resolve(process.cwd(), 'pact/pacts/ot-continuum-web-ot-continuum-api.json')
      ],
      
      // Provider version (for Pact Broker)
      providerVersion: providerConfig.broker.providerVersion,
      
      // Publish verification results
      publishVerificationResult: process.env.CI === 'true',
      
      // State handlers - set up test data for specific states
      stateHandlers: {
        'workflows exist for tenant': async () => {
          console.log('Setting up state: workflows exist for tenant');
          // In a real scenario, you would seed the database here
          // For now, we assume the test database is pre-seeded
          return Promise.resolve('State setup complete');
        },
        
        'work items exist for tenant': async () => {
          console.log('Setting up state: work items exist for tenant');
          return Promise.resolve('State setup complete');
        },
        
        'user has manager role': async () => {
          console.log('Setting up state: user has manager role');
          // JWT token already includes role=admin
          return Promise.resolve('State setup complete');
        },
        
        'user has contributor role and site access': async () => {
          console.log('Setting up state: user has contributor role and site access');
          return Promise.resolve('State setup complete');
        },
        
        'work item exists and user is assignee': async () => {
          console.log('Setting up state: work item exists and user is assignee');
          return Promise.resolve('State setup complete');
        },
        
        'workflow exists': async () => {
          console.log('Setting up state: workflow exists');
          return Promise.resolve('State setup complete');
        }
      },
      
      // Request filter - add authentication headers
      requestFilter: (req: any, res: any, next: any) => {
        const token = process.env.TEST_AUTH_TOKEN || 
          'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3OC0xMjM0LTEyMzQtMTIzNC0xMjM0NTY3ODkwYWIiLCJ0ZW5hbnRfaWQiOiI4NzY1NDMyMS00MzIxLTQzMjEtNDMyMS04NzY1NDMyMTBkY2IiLCJyb2xlIjoiYWRtaW4iLCJzaXRlX2lkcyI6bnVsbCwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIn0.dummysignature';
        
        req.headers['Authorization'] = `Bearer ${token}`;
        next();
      },
      
      // Timeout for provider startup
      timeout: 30000,
      
      // Log level
      logLevel: 'info'
    };

    const verifier = new Verifier(opts);
    
    try {
      const output = await verifier.verifyProvider();
      console.log('Pact Verification Complete!');
      console.log(output);
    } catch (error) {
      console.error('Pact verification failed:', error);
      throw error;
    }
  });
});
